apiVersion: v2
appVersion: 2024.10.13
dependencies:
- name: minio
  repository: https://charts.bitnami.com/bitnami
  version: 14.8.0
- name: nessie
  repository: https://charts.projectnessie.org
  version: 0.99.0
- name: trino
  version: 0.33.0
  repository: https://trinodb.github.io/charts/
- name: kafka
  version: 30.1.8
  repository: https://charts.bitnami.com/bitnami
- name: spark
  version: 9.2.13
  repository: https://charts.bitnami.com/bitnami

description: A full, opinionated data platform deployment in K8s

maintainers:
- name: Caciquetech.org
name: data-platform
version: 0.0.1