apiVersion: v2
appVersion: 2024.10.13
dependencies:
- name: minio
  repository: https://charts.bitnami.com/bitnami
  version: 17.0.21
- name: trino
  version: 1.41.0
  repository: https://trinodb.github.io/charts/
- name: kafka
  version: 32.4.3
  repository: https://charts.bitnami.com/bitnami
- name: spark
  version: 10.0.3
  repository: https://charts.bitnami.com/bitnami
- name: risingwave
  version: 0.2.41
  repository: https://risingwavelabs.github.io/helm-charts/
- name: postgresql
  version: 18.1.1
  repository: https://charts.bitnami.com/bitnami
- name: lakekeeper
  version: 0.8.0
  repository: https://lakekeeper.github.io/lakekeeper-charts/



description: A full, opinionated data platform deployment in K8s

maintainers:
- name: Caciquetech.org
name: data-platform
version: 0.0.1