connector.name=iceberg
iceberg.catalog.type=rest
iceberg.rest-catalog.uri=http://data-platform-nessie:19120
iceberg.rest-catalog.warehouse=s3://warehouse1
iceberg.rest-catalog.parent-namespace=first_namespace
s3.aws-access-key=awsAccessKeyId
s3.aws-secret-key=awsSecretAccessKey
s3.endpoint=http://data-platform-minio:9000
s3.path-style-access=true
s3.region=us-west-2
fs.native-s3.enabled=true