postgresql:
  images:
    tag: 18.0.0
  primary:
    extendedConfiguration: |-
      wal_level = logical
  auth:
    postgresPassword: "hola"
kafka:
  image:
    tag: 4.0.0-debian-12-r10
    repository: bitnamilegacy/kafka
  fullnameOverride: kafka-platform
  sasl:
    client:
      users:
        - user1
      passwords: "user1"
  controller:
    replicaCount: 1
  broker:
    replicaCount: 1
  provisioning:
    enabled: true
    topics:
      - name: test_topic
        partitions: 1
        replicationFactor: 1
        config:
          max.message.bytes: 64000
          flush.messages: 1
      - name: kafka_user_details
        partitions: 1
        replicationFactor: 1
        config:
          max.message.bytes: 64000
          flush.messages: 1
      - name: kafka_user_pay_1
        partitions: 1
        replicationFactor: 1
        config:
          max.message.bytes: 64000
          flush.messages: 1
      - name: kafka_user_pay_2
        partitions: 1
        replicationFactor: 1
        config:
          max.message.bytes: 64000
          flush.messages: 1
      - name: kafka_user_extra_details
        partitions: 1
        replicationFactor: 1
        config:
          max.message.bytes: 64000
          flush.messages: 1
risingwave:
  image:
    tag: v2.6.1
  metaStore:
    postgresql:
      enabled: true
      host: data-platform-postgresql
      port: 5432
      database: risingwave
      authentication:
        username: "postgres"
        password: "hola"
  stateStore:
    dataDirectory: "data"
    minio:
      enabled: true
      endpoint: data-platform-minio:9000
      bucket: risingwave
      authentication:
        username: awsAccessKeyId
        password: awsSecretAccessKey
trino:
  catalogs:
    tpch: |
      connector.name=tpch
      tpch.splits-per-node=4
    tpcds: |
      connector.name=tpcds
      tpcds.splits-per-node=4
    iceberg: |
      connector.name=iceberg
      iceberg.catalog.type=rest
      iceberg.rest-catalog.uri=http://data-platform-lakekeeper:19120/iceberg
      iceberg.rest-catalog.warehouse=warehouse1
      iceberg.file-format=parquet
      s3.aws-access-key=awsAccessKeyId
      s3.aws-secret-key=awsSecretAccessKey
      s3.endpoint=http://data-platform-minio:9000
      s3.path-style-access=true
      s3.region=us-west-2
      fs.native-s3.enabled=true
minio:
  defaultBuckets: "risingwave"
  console:
    image:
      repository: bitnamilegacy/minio-object-browser
      tag: 2.0.2-debian-12-r3
  image:
    tag: 2025.7.23-debian-12-r3
    repository: bitnamilegacy/minio

  auth:
    existingSecret: data-platform-secrets
    rootUserSecretKey: awsAccessKeyId
    rootPasswordSecretKey: awsSecretAccessKey
spark:
  image:
    tag: 4.0.0-debian-12-r20
    repository: bitnamilegacy/spark
