apiVersion: v1
kind: Service
metadata:
  name: duckdb-ui-service
  namespace: data
  labels:
    app: duckdb-ui
spec:
  type: ClusterIP
  selector:
    app: duckdb-ui
  ports:
    - name: http-service
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: https-service
      protocol: TCP
      port: 8443
      targetPort: 8443
