apiVersion: v1
kind: Service
metadata:
  name: nessie-proxy-service
  namespace: data
spec:
  selector:
    app: nessie-proxy-service
  ports:
    - protocol: TCP
      port: 19120
      targetPort: 80
  type: ClusterIP
