apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: data
data:
  nginx.conf: |
    worker_processes 1;
    events {
      worker_connections 1024;
    }
    http {
      merge_slashes off;
      log_format custom_log '$remote_addr - [$time_local] "$request" '
                          'rewritten to "$uri" upstream "$upstream_addr" status $status';
      access_log /var/log/nginx/access.log custom_log;
    
      error_log /var/log/nginx/error.log debug;
    
      server {
        listen 80;

        # Rewrite specific pattern and proxy to the target service
        location ~ ^/iceberg//v1/namespaces/([^/]+)/tables/([^/]+)$ {
          rewrite ^/iceberg//v1/namespaces/([^/]+)/tables/([^/]+)$ /iceberg/v1/main/namespaces/$1/tables/$2;
          proxy_pass http://data-platform-nessie.data.svc.cluster.local:19120;
        }
    
        location / {
            proxy_pass http://data-platform-nessie.data.svc.cluster.local:19120;
        }

    
      }
    }
