[tool.poetry]
name = "pyiceberg-examples"
version = "0.1.0"
description = ""
authors = ["Carlo Scarioni <carlo.scarioni@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pyiceberg = {extras = ["s3fs,hive"], version="^0.7.1"}
pyarrow = "17.0.0"
pandas = "^2.2.3"
avro = "^1.12.0"
gcsfs = "^2024.10.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
